# Generated by Django 4.1.7 on 2023-03-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lazy', models.BooleanField()),
                ('active', models.BooleanField()),
            ],
        ),
    ]
